### ISSUE TITLE
Multiple Content Stores require changes to Settings file

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#40]
So, with Brochard allowing users to have more than one context store, that requires changes to the YAML markup in our Settings files.... so.... How does this look?

``` yaml
Name: Default
State: Running
DataProviders:
   - Name: EntityFramework-InMemory

   - Name: Dapper-SQL
     ConnectionString: <connectionstring> 
     TablePrefix: dp

   - Name: GitHub
RequestUrlHost: localhost:5001
RequestUrlPrefix: 
```

The connection string and table prefix being optional. Name Required.
